[package]
name = "indexify"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]

anyhow = {version="^1"}
async-openai = "*"
async-trait = "*"
axum = {version="^0"} 
axum-macros = {version = "0.3.7"}
batched-fn = {version="^0"}
clap = {version="^4", features=["derive"]}
figment = {version="0.10.8", features=["yaml", "env"]}
oneshot = {version="^0"}
qdrant-client = "^1"
regex = {version="^1"}
rust-bert = {version="0.20.0"}
scraper = {version="^0"}
sea-orm = { version = "^0", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
serde = {version="^1", features=["derive"]}
serde_yaml={version="^0"}
smart-default = {version = "^0"}
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
thiserror = "*"
tokio = { version = "^1", features = ["full"] }
torch-sys = {version="^0"}
tracing = {version="^0"}
tracing-subscriber = {version="^0"}
tracing-test = {version = "^0"}
uuid = {version = "^1", features = ["v4", "fast-rng","macro-diagnostics"]}