[package]
name = "indexify"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]
rust-bert = {version="0.20.0"}
tch = {version="0.10.3"}
anyhow = {version="^1"}
clap = {version="^4", features=["derive"]}
figment = {version="0.10.8", features=["yaml", "env"]}
serde = {version="^1", features=["derive"]}
serde_yaml={version="^0"}
axum = {version="^0"} 
axum-macros = {version = "0.3.7"}
tokio = { version = "^1", features = ["full"] }
tracing = {version="^0"}
tracing-subscriber = {version="^0"}
batched-fn = {version="^0"}
torch-sys = {version="^0"}
oneshot = {version="^0"}
thiserror = "*"
async-openai = "*"
async-trait = "*"
qdrant-client = "^1"
uuid = {version = "^1", features = ["v4", "fast-rng","macro-diagnostics"]}
smart-default = {version = "^0"}
tracing-test = {version = "^0"}
sea-orm = { version = "^0", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }