apiVersion: v1
kind: Secret
metadata:
  name: indexify-secrets
type: Opaque
data:
  postgres_user: cG9zdGdyZXM= # "postgres" base64 encoded
  postgres_password: cG9zdGdyZXM= # "postgres" base64 encoded