name: Manual Build

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-base-extractor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-container
        run: make build-container
      - name: push-container
        run: make push-container
      - name: build-base-extractor-push
        run: make build-base-extractor-push
