name: Manual Build

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build-base-extractor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build-base-extractor
        run: make build-base-extractor
