name: Manual Build
on: workflow_dispatch

jobs:
  build-base-extractor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build-base-extractor
        run: make build-base-extractor
